Repository qiniu/js-sdk, pull requests merged in 2020-07, with the labels that each got.

#462 修复测试文件报错 & sdk 包安全问题
  jest.config.js
  package-lock.json
  package.json
Labels: size/M

#460 修复非浏览器环境下没有 window 对象导致的错误
  README.md
  package.json
  src/__tests__/api.test.ts
  src/api.ts
  src/upload/base.ts
  src/utils.ts
Labels: lgtm, size/M

#461 add badges of build, release and coverage
  .travis.yml
  README.md
Labels: size/XS

#463 扩展 key 的支持范围
  README.md
  package-lock.json
  package.json
  src/__tests__/utils.test.ts
  src/api.ts
  src/index.ts
  src/upload/base.ts
  src/utils.ts
Labels: size/M
