Repository qiniu/js-sdk, pull requests merged in 2021-05, with the labels that each got.

#505 添加支持多 host 自动切换 & 补全测试
  README.md
  package.json
  src/api/index.mock.ts
  src/api/index.test.ts
  src/api/index.ts
  src/config/index.ts
  src/config/region.ts
  src/errors/index.ts
  src/index.ts
  src/logger/index.test.ts
  src/logger/index.ts
  src/logger/report-v3.test.ts
  src/upload/base.ts
  src/upload/direct.ts
  src/upload/hosts.test.ts
  src/upload/hosts.ts
  src/upload/index.test.ts
  src/upload/index.ts
  src/upload/resume.ts
  src/utils/compress.ts
  src/utils/config.test.ts
  src/utils/config.ts
  src/utils/helper.test.ts
  src/utils/helper.ts
  src/utils/index.ts
  webpack.prod.js
Labels: size/XXL

#510 优化上传 Error 类型
  src/errors/index.ts
  src/upload/index.ts
Labels: size/S

#511 修复 eslint & 为 QiniuRequestError 添加 data 字段 & 为 chunk 添加 isLocalCached 字段
  .travis.yml
  README.md
  package.json
  src/api/index.mock.ts
  src/api/index.test.ts
  src/errors/index.ts
  src/image/index.test.ts
  src/logger/index.test.ts
  src/upload/base.ts
  src/upload/hosts.ts
  src/upload/index.test.ts
  src/upload/index.ts
  src/upload/resume.ts
  src/utils/compress.ts
  src/utils/config.ts
  src/utils/helper.test.ts
  src/utils/helper.ts
  src/utils/pool.test.ts
  types/window.d.ts
Labels: size/L

#512 优化缓存调用逻辑
  package.json
  src/upload/base.ts
  src/upload/index.test.ts
  src/upload/resume.ts
Labels: size/L
