Repository qiniu/js-sdk, pull requests merged in 2021-04, with the labels that each got.

#491 init vue example
  .gitignore
  examples/vue-v2/.gitignore
  examples/vue-v2/README.md
  examples/vue-v2/babel.config.js
  examples/vue-v2/package.json
  examples/vue-v2/public/favicon.ico
  examples/vue-v2/public/index.html
  examples/vue-v2/src/App.vue
  examples/vue-v2/src/assets/logo.png
  examples/vue-v2/src/components/HelloWorld.vue
  examples/vue-v2/src/main.js
  examples/vue-v2/yarn.lock
  examples/vue-v3/.gitignore
  examples/vue-v3/README.md
  examples/vue-v3/babel.config.js
  examples/vue-v3/package.json
  examples/vue-v3/public/favicon.ico
  examples/vue-v3/public/index.html
  examples/vue-v3/src/App.vue
  examples/vue-v3/src/assets/logo.png
  examples/vue-v3/src/components/HelloWorld.vue
  examples/vue-v3/src/main.js
  examples/vue-v3/yarn.lock
Labels: size/XXL

#493 Revert "init vue example (#491)"
  .gitignore
  examples/vue-v2/.gitignore
  examples/vue-v2/README.md
  examples/vue-v2/babel.config.js
  examples/vue-v2/package.json
  examples/vue-v2/public/favicon.ico
  examples/vue-v2/public/index.html
  examples/vue-v2/src/App.vue
  examples/vue-v2/src/assets/logo.png
  examples/vue-v2/src/components/HelloWorld.vue
  examples/vue-v2/src/main.js
  examples/vue-v2/yarn.lock
  examples/vue-v3/.gitignore
  examples/vue-v3/README.md
  examples/vue-v3/babel.config.js
  examples/vue-v3/package.json
  examples/vue-v3/public/favicon.ico
  examples/vue-v3/public/index.html
  examples/vue-v3/src/App.vue
  examples/vue-v3/src/assets/logo.png
  examples/vue-v3/src/components/HelloWorld.vue
  examples/vue-v3/src/main.js
  examples/vue-v3/yarn.lock
Labels: size/XXL

#498 fix: type define of compress.ts
  README.md
  src/compress.ts
Labels: size/XS

#499 [KODO-12017] 添加生产模式输出详细日志功能及配置
  .gitignore
  README.md
  src/index.ts
  src/logger/index.test.ts
  src/logger/index.ts
  src/logger/report-v3.test.ts
  src/logger/report-v3.ts
  src/statisticsLog.ts
  src/upload/base.ts
  src/upload/direct.ts
  src/upload/index.ts
  src/upload/resume.ts
  src/utils.ts
  test/demo1/main.js
  test/demo2/index.js
  tsconfig.json
Labels: size/XL

#502 升级依赖 & 升级版本 3.1.3
  package-lock.json
  package.json
Labels: size/XXL

#503 [BUG] 修复 initBeforeUploadChunks 错误未中断的行为
  package-lock.json
  package.json
  src/upload/resume.ts
Labels: size/S

#504 优化项目结构
  package.json
  src/__tests__/utils.test.ts
  src/api/index.test.ts
  src/api/index.ts
  src/config/index.ts
  src/image/index.test.ts
  src/image/index.ts
  src/index.ts
  src/logger/index.test.ts
  src/logger/report-v3.test.ts
  src/upload/base.ts
  src/upload/direct.ts
  src/upload/index.ts
  src/upload/resume.ts
  src/utils/base64.test.ts
  src/utils/base64.ts
  src/utils/compress.ts
  src/utils/helper.test.ts
  src/utils/helper.ts
  src/utils/index.ts
  src/utils/observable.ts
  src/utils/pool.test.ts
  src/utils/pool.ts
  tsconfig.json
Labels: size/L
